name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest] # Define the operating systems to test on
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Install dependencies
      run: |
        rustup component add clippy
        rustup component add rustfmt
        cargo install cargo-tarpaulin

    - name: Run tests with coverage
      run: |
        cargo tarpaulin --exclude-files src/main.rs
        cargo tarpaulin --ignore-tests --out Xml
        
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
        fail_ci_if_error: true
      env:
        CODECOV_DEBUG: "true"
        slug: ArneilPaulPolican/polkadot-cli


